### ISSUE TITLE
What's the point of this NPM module?

### ISSUE THREAD

**Issue by sghiassy** [sindresorhus/user-home#4]
I don't get the point of this NPM package? It proxies 1:1 to `os-homedir`. Why not just `require('os-homedir')` instead?

I might be missing something, so thanks for any insights.

Cheers,

**Comment by sindresorhus** [comment]
This module was made long before `os-homedir`. When Node.js decided to add a native method for getting the user's home directory, I made a polyfill matching its API and decided to depend on it here, so not to have duplicate code. The main reason this one is still around is that lots of modules depend on it and I see no reason to inconvenience dependents by deprecating this. This one also gets the home directory on startup and returns a string rather than exposing a method, so it's faster, and I prefer this API. Modules are cheap in Node.js, so doesn't matter. Use whichever you prefer. I'm going to continue using this.

**Comment by sghiassy** [comment]
(thumbsup)
